% =============================================
% Stress-Vsv 指定参数脚本（统一黑白论文风格）
% 公式: V(P) = A + K*P - B*exp(-P*D)
% =============================================
clear;
clc;

%% ===================== 数据初始化 =====================
cd(fileparts(mfilename("fullpath")));

params = jsondecode( ...
    fileread('../../../../../06_ProcessedData/parameters.json'));

P = params.P(:) / 1e6;   % MPa

nonellipse_vsv = readmatrix( ...
    '../../../../../06_ProcessedData/03_velocity/n_20_degree_0/vsv/vsv_nonellipse.csv');

ellipse_vsv = readmatrix( ...
    '../../../../../06_ProcessedData/03_velocity/n_20_degree_0/vsv/vsv_ellipse.csv');

cycle = 6;

markerIndex = 1:15:length(P);

%% ===================== 手动指定参数 =====================

A_nonellipse = [1258.42 1257.62 1256.76 1255.7 1255.82 1255.36];
K_nonellipse = [5.23025e-11 3.65203e-14 1.08786e-11 1.22936e-11 5.95116e-12 2.07697e-12];
B_nonellipse = [96.2886 93.9376 92.8827 92.5108 91.7318 90.233];
D_nonellipse = [0.0617915 0.0768848 0.0800309 0.102033 0.111137 0.134843];

A_ellipse = [1273.08 1266.54 1263.16 1260.84 1258.63 1256.79];
K_ellipse = [1.15652e-11 9.24432e-11 8.91073e-11 6.70927e-13 8.96045e-12 2.34405e-11];
B_ellipse = [116.885 112.517 108.264 107.004 105.715 104.515];
D_ellipse = [0.0320911 0.0467108 0.050196 0.0618646 0.0767976 0.114407];

params_nonellipse = [A_nonellipse', K_nonellipse', B_nonellipse', D_nonellipse'];
params_ellipse = [A_ellipse', K_ellipse', B_ellipse', D_ellipse'];

%% ===================== 模型函数 =====================
model_func = @(params, P) ...
    params(1) + params(2)*P - params(3)*exp(-P*params(4));

%% ===================== R²计算 =====================
resnorm_nonellipse = zeros(cycle,1);
resnorm_ellipse = zeros(cycle,1);

nonellipse_r2 = zeros(cycle,1);
ellipse_r2 = zeros(cycle,1);

for i = 1:cycle

    y_non = nonellipse_vsv(:,i);
    yfit_non = model_func(params_nonellipse(i,:), P);

    SS_res_non = sum((y_non - yfit_non).^2);
    SS_tot_non = sum((y_non - mean(y_non)).^2);

    resnorm_nonellipse(i) = SS_res_non;
    nonellipse_r2(i) = 1 - SS_res_non / SS_tot_non;

    y_ell = ellipse_vsv(:,i);
    yfit_ell = model_func(params_ellipse(i,:), P);

    SS_res_ell = sum((y_ell - yfit_ell).^2);
    SS_tot_ell = sum((y_ell - mean(y_ell)).^2);

    resnorm_ellipse(i) = SS_res_ell;
    ellipse_r2(i) = 1 - SS_res_ell / SS_tot_ell;

end

%% ===================== 全局绘图参数 =====================
FONT_NAME = 'Times New Roman';

FONT_SIZE_LABEL = 14;
FONT_SIZE_AXIS = 14;
FONT_SIZE_TITLE = 14;
FONT_SIZE_LEGEND = 13;
FONT_SIZE_TEXT = 10;

LINE_WIDTH = 1.8;
MARKER_SIZE = 5;

subTitleList = { ...
    '(a)', ...
    '(b)', ...
    '(c)', ...
    '(d)', ...
    '(e)', ...
    '(f)'};

modelParams = {'20AR1', '16AR1+4AR2', '12AR1+8AR2', ...
               '8AR1+12AR2', '4AR1+16AR2', '20AR2'};

%% ===================== 拟合结果图 =====================
fig1 = figure( ...
    'Color',[1 1 1], ...
    'Position',[0 0 900 1200]);

tiledlayout(3,2, ...
    'TileSpacing','compact', ...
    'Padding','compact');

ax = gobjects(1,6);

for g = 1:cycle

    ax(g) = nexttile;

    hold on;

    nonellipse_data = nonellipse_vsv(:,g);
    ellipse_data = ellipse_vsv(:,g);

    nonellipse_fit = model_func(params_nonellipse(g,:), P);
    ellipse_fit = model_func(params_ellipse(g,:), P);

    % ===================== 椭圆数据 =====================
    p1 = plot(P, ellipse_data, '-sk', ...
        'LineWidth', LINE_WIDTH, ...
        'MarkerSize', MARKER_SIZE, ...
        'MarkerFaceColor','w', ...
        'MarkerIndices', markerIndex);

    % ===================== 非椭圆数据 =====================
    p2 = plot(P, nonellipse_data, '-^k', ...
        'LineWidth', LINE_WIDTH, ...
        'MarkerSize', MARKER_SIZE, ...
        'MarkerFaceColor','w', ...
        'MarkerIndices', markerIndex);

    % ===================== 拟合线 =====================
    plot(P, ellipse_fit, 'k-', ...
        'LineWidth',1.0);

    plot(P, nonellipse_fit, 'k--', ...
        'LineWidth',1.0);

    % ===================== 标题 =====================
    title(subTitleList{g}, ...
        'FontSize', FONT_SIZE_TITLE, ...
        'FontWeight','normal', ...
        'FontName', FONT_NAME);

    % ===================== 坐标轴 =====================
    xlabel('Stress (MPa)', ...
        'FontSize', FONT_SIZE_LABEL, ...
        'FontName', FONT_NAME);

    ylabel('V_{SV} (m/s)', ...
        'FontSize', FONT_SIZE_LABEL, ...
        'FontName', FONT_NAME, ...
        'Interpreter','tex');

    ylim([1140 1290]);

    % ===================== R² =====================
    ellipse_r2_str = sprintf( ...
        'Ellipse R^2 = %.4f', ...
        ellipse_r2(g));

    nonellipse_r2_str = sprintf( ...
        'Nonellipse R^2 = %.4f', ...
        nonellipse_r2(g));

    text(0.95,0.18,ellipse_r2_str, ...
        'Units','normalized', ...
        'FontSize',FONT_SIZE_TEXT, ...
        'FontName',FONT_NAME, ...
        'HorizontalAlignment','right');

    text(0.95,0.12,nonellipse_r2_str, ...
        'Units','normalized', ...
        'FontSize',FONT_SIZE_TEXT, ...
        'FontName',FONT_NAME, ...
        'HorizontalAlignment','right');

    % ===================== 拟合公式 =====================
    ellipse_eq = sprintf( ...
        'V_{SV,Ellipse}=%.1f+%.1eP-%.1fe^{-%.3fP}', ...
        params_ellipse(g,1), ...
        params_ellipse(g,2), ...
        params_ellipse(g,3), ...
        params_ellipse(g,4));

    nonellipse_eq = sprintf( ...
        'V_{SV,Nonellipse}=%.1f+%.1eP-%.1fe^{-%.3fP}', ...
        params_nonellipse(g,1), ...
        params_nonellipse(g,2), ...
        params_nonellipse(g,3), ...
        params_nonellipse(g,4));

    text(0.95,0.32,ellipse_eq, ...
        'Units','normalized', ...
        'FontSize',FONT_SIZE_TEXT, ...
        'FontName',FONT_NAME, ...
        'HorizontalAlignment','right', ...
        'Interpreter','tex');

    text(0.95,0.26,nonellipse_eq, ...
        'Units','normalized', ...
        'FontSize',FONT_SIZE_TEXT, ...
        'FontName',FONT_NAME, ...
        'HorizontalAlignment','right', ...
        'Interpreter','tex');

    % ===================== 坐标轴格式 =====================
    set(gca, ...
        'FontName', FONT_NAME, ...
        'FontSize', FONT_SIZE_AXIS, ...
        'LineWidth',1);

    box on;

end

linkaxes(ax,'xy');

%% ===================== 图例 =====================
lgd1 = legend([p1,p2], ...
    {'Ellipse model','Nonelliptical model'}, ...
    'Orientation','horizontal', ...
    'FontSize', FONT_SIZE_LEGEND, ...
    'FontName', FONT_NAME);

lgd1.Layout.Tile = 'north';

%% ===================== 参数趋势图 =====================
fig2 = figure( ...
    'Color',[1 1 1], ...
    'Position',[100 100 1200 800]);

tiledlayout(2,2, ...
    'TileSpacing','compact', ...
    'Padding','compact');

groups = 1:cycle;

ellipseParams = { ...
    params_ellipse(:,1), ...
    params_ellipse(:,2), ...
    params_ellipse(:,3), ...
    params_ellipse(:,4)};

nonellipseParams = { ...
    params_nonellipse(:,1), ...
    params_nonellipse(:,2), ...
    params_nonellipse(:,3), ...
    params_nonellipse(:,4)};

yLabels = { ...
    'A value', ...
    'K value', ...
    'B value', ...
    'D value'};

standardLines = [1254.7, 0, 71.5, NaN];

yLimits = { ...
    [1250 1280], ...
    [-1 1], ...
    [60 120], ...
    [0.02 0.2]};

for i = 1:4

    nexttile;

    hold on;

    plot(groups, ellipseParams{i}, '-sk', ...
        'LineWidth',2, ...
        'MarkerSize',8, ...
        'MarkerFaceColor','w');

    plot(groups, nonellipseParams{i}, '-^k', ...
        'LineWidth',2, ...
        'MarkerSize',8, ...
        'MarkerFaceColor','w');

    % 标准线
    yline(standardLines(i), 'k--', ...
        'LineWidth',1.2);

    xticks(1:6);

    xticklabels(modelParams);

    ylabel(yLabels{i}, ...
        'FontSize',FONT_SIZE_LABEL, ...
        'FontName',FONT_NAME);

    title(subTitleList{i}, ...
        'FontSize',FONT_SIZE_TITLE, ...
        'FontWeight','normal', ...
        'FontName',FONT_NAME);

    ylim(yLimits{i});

    set(gca, ...
        'FontName',FONT_NAME, ...
        'FontSize',FONT_SIZE_AXIS, ...
        'LineWidth',1);

    grid on;
    box on;

end

legend({'Ellipse model', ...
        'Nonelliptical model', ...
        'Standard value'}, ...
        'Location','best', ...
        'FontSize',FONT_SIZE_LEGEND, ...
        'FontName',FONT_NAME);